# File Transformation POC

trigger:
- none

pool:
  vmImage: windows-latest

variables:
  resources.tags.Env.1:  'testtag'
  resources.name:  'testname'
  outputs:  'testoutput'

steps:
# - script: dir /s

- task: FileTransform@1
  inputs:
    # folderPath: 'D:\a\1\s\'
    folderPath:  '$(System.DefaultWorkingDirectory)'
    fileType: json
    targetFiles: 'azuredeploy.json'

# File transform
# Replace tokens with variable values in XML or JSON configuration files
#- task: FileTransform@1
#  inputs:
    #folderPath: '$(System.DefaultWorkingDirectory)/**/*.zip' 
    #fileType: # Optional. Options: xml, json
    #targetFiles: # Optional