# File Transformation POC

trigger:
- none

pool:
  vmImage: windows-latest

variables:
  resources.tags.Owner:  'joecro'
  parameters.storageAccountName.minLength:  '4'
  functions:  'test'

steps:
- script: dir /s

- task: FileTransform@1
  inputs:
    folderPath: 'D:\a\1\s\azuredeploy.json'
    targetFiles: 'azuredeploy.json'
    fileType: json
