# File Transformation POC

trigger:
- none

pool:
  vmImage: windows-latest

variables:
  resources.tags.Owner:  'joecro'
  parameters.storageAccountName.minLength:  '4'
  functions:  'test'

steps:
- task: FileTransform@1
  displayName: 'File transformation:  azuredeploy.json'
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)'
    targetFiles: '**/azuredeploy.json'
    fileType: json
