# File Transformation POC

trigger:
- none

pool:
  vmImage: windows-latest

variables:
  resources.tags.Owner:  'joecro'
  parameters.storageAccountName.minLength:  '4'
  functions:  'test'

steps:
- task: FileTransform@1
  inputs:
    folderPath: 'a130138/01_TemplateRepo'
    targetFiles: '**/azuredeploy.json'
    fileType: json
