# Azure Storage Acct Deploy via TF

pool:
    vmImage: ubuntu-latest
trigger:
    - none
steps:
- checkout: self
  persistCredentials: true

- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'Dev_Azure_10002_CloudSandbox3(239c71f8-a24e-41d1-96f6-b4f834a1f615)'
    backendAzureRmSubscriptionId: '239c71f8-a24e-41d1-96f6-b4f834a1f615'
    backendAzureRmResourceGroupName: 'JoePOC1'
    allowTelemetryCollection: false
    workingDirectory: '$(System.DefaultWorkingDirectory)/01_AzStorage/03_TF'
- task: TerraformCLI@0
  inputs:
    command: 'validate'
    backendType: 'azurerm'
    backendServiceArm: 'Dev_Azure_10002_CloudSandbox3(239c71f8-a24e-41d1-96f6-b4f834a1f615)'
    backendAzureRmSubscriptionId: '239c71f8-a24e-41d1-96f6-b4f834a1f615'
    backendAzureRmResourceGroupName: 'JoePOC1'
    allowTelemetryCollection: false
    workingDirectory: '$(System.DefaultWorkingDirectory)/01_AzStorage/03_TF'
- task: TerraformCLI@0
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/01_AzStorage/03_TF'
    environmentServiceName: 'Dev_Azure_10002_CloudSandbox3(239c71f8-a24e-41d1-96f6-b4f834a1f615)'
    providerAzureRmSubscriptionId: '239c71f8-a24e-41d1-96f6-b4f834a1f615'
    backendAzureRmResourceGroupName: 'JoePOC1'
    allowTelemetryCollection: false
- task: TerraformCLI@0
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/01_AzStorage/03_TF'
    environmentServiceName: 'Dev_Azure_10002_CloudSandbox3(239c71f8-a24e-41d1-96f6-b4f834a1f615)'
    providerAzureRmSubscriptionId: '239c71f8-a24e-41d1-96f6-b4f834a1f615'
    backendAzureRmResourceGroupName: 'JoePOC1'
    allowTelemetryCollection: false