# Azure Storage Acct Deploy via TF

pool:
    vmImage: windows-latest
trigger:
    - none
steps:
- checkout: self
  persistCredentials: true

- task: TerraformInstaller@0
  inputs:
    terraformVersion: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller
    



