# Azure Storage Create Validation

# Variables
#   ${env:AZLOCATION}


name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
# Set MyRunNumber
variables:
  MyRunNumber: '1.0.0-CI+$(Build.BuildNumber)'

trigger:
# - main
  - none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo $(MyRunNumber) # display MyRunNumber
- script: echo $(Build.BuildNumber) # display Run Number
- script: echo '$(Build.BuildNumber)' # outputs customized build number like project_def_master_20200828.1
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Dev_Azure_10002_CloudSandbox3(239c71f8-a24e-41d1-96f6-b4f834a1f615)'
    subscriptionId: '239c71f8-a24e-41d1-96f6-b4f834a1f615'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'JoePOC1'
    location: '${env:AZLOCATION}'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/a130138/01_TemplateRepo/main/01_AzStorage/01_AzStorageAccount/01_Create/01_Validation/azuredeploy.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/a130138/01_TemplateRepo/main/01_AzStorage/01_AzStorageAccount/01_Create/01_Validation/azuredeploy.parameters.json'

    deploymentMode:
      ##  Incremental
        Validation
      ##  Complete

